### ISSUE TITLE
User should be able to sign up to use the web app

### ISSUE THREAD

**Issue by agneym** [coronasafe/journal#2]
Sign up collects following details from the user:

* Name
* Phone number
* Date of Birth of the user

Authentication enforces uniqueness of phone number + date of birth on the backend.

Ref: #1

Returns a token (cookie or otherwise) stored locally on the device.

**Comment by midhunkrishna** [comment]
@agneym I can pick this up.

**Comment by ittyjose** [comment]
Please find the PR for this issue link: https://github.com/coronasafe/journal/pull/17
It includes the basic design for the signup and OTP page

@midhunkrishna @agneym

**Comment by agneym** [comment]
@midhunkrishna Do check if you are able to use UI from the same.
