### ISSUE TITLE
User should be able to mark a visit to establishment

### ISSUE THREAD

**Issue by agneym** [coronasafe/journal#30]
When user scans a QR code (#3), the details from QR code (#5) needs to be send to the backend. 

Here a "Visit" is created with details of:
* current user
* current time as entry time
* establishment identifier (from scanned QR code)
* empty exit time

For expansion purposes, would like to have Visit to have polymorphic link to Establishment as other types could be added in the future.

**Comment by unnitallman** [comment]
I will pick this up @agneym
