### ISSUE TITLE
./bin/setup exits with an error

### ISSUE THREAD

**Issue by unnitallman** [coronasafe/journal#33]
This happens because User schema has been changed. It has no `email` now, but has `phone_number`, `date_of_birth` etc instead. But this change is not reflected while loading sample data.

**Comment by unnitallman** [comment]
I have a fix ready for this. But unable to push the branch. 
<img width="955" alt="Screenshot 2020-07-16 at 4 47 05 PM" src="https://user-images.githubusercontent.com/58798/87665196-2cd52c80-c784-11ea-882c-31b8e988efc5.png">

@agneym Do I have the required access?

**Comment by agneym** [comment]
@unnitallman Can you try raising a PR from fork of this repository?

**Comment by unnitallman** [comment]
@agneym https://github.com/coronasafe/journal/pull/34
