### ISSUE TITLE
User phone number should be verified by OTP

### ISSUE THREAD

**Issue by agneym** [coronasafe/journal#4]
On user sign up page, the phone number entered by user has to be verified first.

@bodhish for docs on existing service to do that.

**Comment by bodhish** [comment]
@tomahawk-pilot

**Comment by agneym** [comment]
@tomahawk-pilot Any details on this?

**Comment by unnitallman** [comment]
API endpoint: https://github.com/coronasafe/journal/blob/develop/doc/api.md#otp-verification

Once we have the endpoint, integrate it here: https://github.com/unnitallman/journal/blob/6cc0c45e9d143efbb91ebca8476846bc8249cc23/app/services/otp_service.rb#L11

**Comment by unnitallman** [comment]
OTP service has been integrated: https://github.com/coronasafe/journal/pull/86
