### ISSUE TITLE
Ongoing vists page

### ISSUE THREAD

**Issue by agneym** [coronasafe/journal#45]
* Show merchant name and address next to ongoing visits list

**Comment by amaljosea** [comment]
@agneym Checking this

**Comment by agneym** [comment]
@amaljosea Checkout the [doc](https://github.com/coronasafe/journal/blob/develop/doc/api.md#log-a-new-visit) for the concerned API. You would need latest develop if you have issues signing in

**Comment by amaljosea** [comment]
@agneym Is this api is working for you? 
![Screenshot 2020-07-18 at 11 59 28 AM](https://user-images.githubusercontent.com/26934320/87846521-24990080-c8ee-11ea-9654-8ebb1ea18b22.png)

**Comment by amaljosea** [comment]
Seems like
Apis `/api/v1/visits/ongoing` and `/api/v1/visits` not working for some scenarios.

user has no visit -  api is working
user has 1 visit -  api is working
user has 2 visit -  **api is not working**
user has more than 2 visits - **api is not working**

**Comment by agneym** [comment]
cc @unnitallman

**Comment by unnitallman** [comment]
> Seems like
> Apis `/api/v1/visits/ongoing` and `/api/v1/visits` not working for some scenarios.
> 
> user has no visit - api is working
> user has 1 visit - api is working
> user has 2 visit - **api is not working**
> user has more than 2 visits - **api is not working**

https://github.com/coronasafe/journal/issues/50#issuecomment-660449232
