### ISSUE TITLE
Merchant should be able generate a QR code from the application

### ISSUE THREAD

**Issue by agneym** [coronasafe/journal#5]
For MVP, merchant does not need to have a login to application.

The merchant page should enable to collect:
* Establishment name
* Phone number
* Address 

This has to be saved on to the database and a QR code is generated.

QR code contains following details:
* typeof "establishment" (this is for extension purposes later on, other types can be added)
* backend identifier for merchant/establishment

**Comment by agneym** [comment]
Backend and API integration is pending on this ticket.

**Comment by midhun-at-vineti** [comment]
@agneym Picking this up. 

NOTE:
This issue only tracks the generation of QR code that is linked to a uuid. 

Logical Flow of this API:
- When Merchant user posts the merchant information to the backend
--> The backend system creates a merchant record in the db, with a uuid field. 

Logical Flow of QR Code Generator on the back end:
- Given a record with a universal uniq identifier, it generates a QR code that exposes only this uniq identifier

**Comment by agneym** [comment]
@midhun-at-vineti  Would like the QR code to also hold a type of operator.

* typeof "establishment" (this is for extension purposes later on, other types can be added)
