### ISSUE TITLE
Questions related to the background job that deletes user data after a month

### ISSUE THREAD

**Issue by unnitallman** [coronasafe/journal#52]
1. Why do we have to delete the QR Code after a month? https://github.com/coronasafe/journal/blob/24aeb715838348700323862132050531e43527cd/app/jobs/cleanup_old_data_job.rb#L8

2. Logging a visit  as of now doesn't change the user's `updated_at` field. User's `updated_at` remains the same as his `created_at`. So deleting a user based on his `updated_at` will just remove the user and ALL HIS VISITS from the system after 30 days of his first login. https://github.com/coronasafe/journal/blob/24aeb715838348700323862132050531e43527cd/app/jobs/cleanup_old_data_job.rb#L9

3. Shouldn't we be deleting all visits which are older than 30 days? And also delete the user if his last visit was logged more than 30 days ago?

**Comment by agneym** [comment]
1. QR Codes are not necessary at all at the current point, we are using Google's Chart API service to generate QR codes.
2. yes, we should only be storing the visit data of a user for a period of 30 days.

**Comment by agneym** [comment]
@tachyons Can you take a look at this?

**Comment by tachyons** [comment]
Actually I wanted to make consensus about which all data need to be deleted before merging the PR as I wasn't involved in architecture decisions. But forgot to include that in the PR description. 

Motivation behind checking updated_at was delete user data if the user was inactive for a month.

**Comment by agneym** [comment]
@bodhish Let me know what you think here, I'm of the assumption that any user visit data older than 30 days is to be deleted. The user data itself can remain within the system

**Comment by bodhish** [comment]
All logs greater than 30 days should be cleared.
This is super critical in terms of privacy. 

We could also delete users after 30 days of inactivity.

**Comment by unnitallman** [comment]
> All logs greater than 30 days should be cleared.
> This is super critical in terms of privacy.
> 
> We could also delete users after 30 days of inactivity.

This PR will take care of this. https://github.com/coronasafe/journal/pull/60
