### ISSUE TITLE
Add field visit_id to the visit list apis

### ISSUE THREAD

**Issue by amaljosea** [coronasafe/journal#57]
To _mark exit on an ongoing visit_  as specified in the [doc](https://github.com/coronasafe/journal/blob/develop/doc/api.md#mark-exit-on-an-ongoing-visit), field `visit_id` is needed.

Seems like the field `visit_id` is now not present in the response of these apis.

[Log a new visit](https://github.com/coronasafe/journal/blob/develop/doc/api.md#log-a-new-visit)
[Get all visits of a user](https://github.com/coronasafe/journal/blob/develop/doc/api.md#get-all-visits-of-a-user-most-recent-one-first)
[Get ongoing visits of a user](https://github.com/coronasafe/journal/blob/develop/doc/api.md#get-ongoing-visits-of-a-user-most-recent-one-first)

**Comment by agneym** [comment]
@amaljosea The linked API is using `visitable_id` and `visitable_type`, are you sure it needs `visit_id`?
