### ISSUE TITLE
List all establishments in admin dashboard

### ISSUE THREAD

**Issue by edwinbbu** [coronasafe/journal#70]
Api required to list all establishments in admin.

Related to #9

**Comment by unnitallman** [comment]
@unnitallman _a

**Comment by unnitallman** [comment]
This is done @edwinbbu 

API: https://github.com/coronasafe/journal/blob/70-filtered-merchants-list/doc/api.md#merchants-filter

To get the list of local bodies, to display as drop downs for the filter, use the `Local bodies` end-point. https://github.com/coronasafe/journal/blob/70-filtered-merchants-list/doc/api.md#local-bodies
