### ISSUE TITLE
Merchant should be able to select local body on registration

### ISSUE THREAD

**Issue by agneym** [coronasafe/journal#71]
List of local bodies as available here: https://github.com/coronasafe/datastore/tree/master/JSON

Merchant can select one local body off the list that is saved to the database at the time of registration

**Comment by edwinbbu** [comment]
We can have a select field during merchant registration. The user can select the local body. 
We can pass in `lb_code` which is unique in the api the call @agneym 

No api and db support for local bodies @unnitallman

**Comment by unnitallman** [comment]
@edwinbbu I have done this. Please go through https://github.com/coronasafe/journal/pull/77#issue-454325993

/cc @agneym
