### ISSUE TITLE
Admin should be able to select from and to date for route map

### ISSUE THREAD

**Issue by agneym** [coronasafe/journal#76]
Related to #8 
API: https://github.com/coronasafe/journal/blob/develop/doc/api.md#routemap-for-a-user

Backend defaults to last 7 days, but date can be customized. Requires two date pickers for start and end date, end date needs to be validated to be less than start date.

**Comment by edwinbbu** [comment]
I'll work on it.

**Comment by ittyjose** [comment]
Ref https://github.com/coronasafe/journal/pull/82
Also adds the min date requirement for the establishment 'to' feild

@agneym
