### ISSUE TITLE
Admin should be able to generate a user's route map

### ISSUE THREAD

**Issue by agneym** [coronasafe/journal#8]
Admin should be able to generate a list of establishments visited by the user in case they test positive for the virus.

**Comment by agneym** [comment]
Ref: https://github.com/coronasafe/journal/issues/7#issuecomment-657990357

**Comment by unnitallman** [comment]
API endpoint: https://github.com/coronasafe/journal/blob/develop/doc/api.md#routemap-for-a-user

**Comment by agneym** [comment]
@unnitallman We need to consolidate the two APIs required here. The current API flow dictates two steps:
1. search for user using phone number and date of birth
2. use the returned user ID to fetch routes.
But since phone number is unique in the first place, the search makes no sense, also with a user id that can be guessed, it's simply opening up the second API to all users.
Instead we need to have a single API that can look up the user by phone number and date of birth, return user details (the name just for confirmation that admin has the right user) and route map.

**Comment by unnitallman** [comment]
@agneym The user table uses `integer` ids. That is not a good thing and thats what makes it "guessable". I will change it to `uuid`. If so do you think, we will still need to merge the two APIs ? its not difficult to do, just let me know.

**Comment by unnitallman** [comment]
https://github.com/coronasafe/journal/pull/65 converts ID of user table from integer to UUID. Haven't merged it yet. Once this is done, existing database will need to reset using `./bin/setup` since user -> visit relationships will be affect by this change.

**Comment by agneym** [comment]
That sounds fine for now, we can review the UI later if necessary
