### ISSUE TITLE
Admin should be able to filter visits by establishment, date and time

### ISSUE THREAD

**Issue by agneym** [coronasafe/journal#9]
Admin should be able to enter an establishment name, a particular date and time and receive filtered details on users who have been in and out during the particular time period.

**Comment by unnitallman** [comment]
API endpoint: https://github.com/coronasafe/journal/blob/develop/doc/api.md#visits-filter

**Comment by ittyjose** [comment]
Ref https://github.com/coronasafe/journal/pull/79

@agneym
